# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pro',
            options={'ordering': ['-id'], 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u9644\u52a0\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='pro',
            name='app_id',
            field=models.IntegerField(default=111111, verbose_name='app_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pro',
            name='secret',
            field=models.CharField(default='asdfasdfasdf', max_length=100, verbose_name='app_id'),
            preserve_default=False,
        ),
    ]
