# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IspPhoneBill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('call_pay', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isp_phone_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IspPhoneCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('trade_type', models.IntegerField()),
                ('trade_time', models.CharField(blank=True, max_length=20, null=True)),
                ('call_time', models.CharField(blank=True, max_length=20, null=True)),
                ('receive_phone', models.CharField(max_length=64)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isp_phone_call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IspPhoneSms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('sms_type', models.IntegerField()),
                ('sms_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_phone', models.CharField(max_length=64)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isp_phone_sms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IspUserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('phone_service_password', models.CharField(blank=True, max_length=16, null=True)),
                ('user_source', models.CharField(blank=True, max_length=30, null=True)),
                ('real_name', models.CharField(max_length=64)),
                ('idcard', models.CharField(max_length=64)),
                ('phone_remain', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_time', models.CharField(blank=True, max_length=64, null=True)),
                ('isp', models.CharField(blank=True, max_length=4, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isp_user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('create_time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCallRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('trade_type', models.IntegerField()),
                ('trade_time', models.CharField(blank=True, max_length=20, null=True)),
                ('call_time', models.CharField(blank=True, max_length=20, null=True)),
                ('receive_phone', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_call_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCheckIdcardInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('idcard', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('issuing', models.CharField(blank=True, max_length=128, null=True)),
                ('idcard_passed_time', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_check_idcard_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('contact_phone', models.CharField(max_length=64)),
                ('contact_name', models.CharField(max_length=64)),
                ('relation', models.CharField(blank=True, max_length=64, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserContactsPhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('contact_phone', models.CharField(max_length=64)),
                ('contact_name', models.CharField(max_length=64)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_contacts_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFaceInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('face_type', models.IntegerField()),
                ('face_url', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_face_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserIdcardInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('idcard', models.CharField(max_length=64)),
                ('race', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('idcard_url_positive', models.CharField(blank=True, max_length=128, null=True)),
                ('issuing', models.CharField(blank=True, max_length=128, null=True)),
                ('idcard_passed_time', models.BigIntegerField(blank=True, null=True)),
                ('idcard_url_negative', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_idcard_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('social_identity', models.IntegerField(blank=True, null=True)),
                ('expected_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('current_live_address', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.IntegerField()),
                ('education_level', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=64)),
                ('sms_type', models.IntegerField()),
                ('sms_date', models.CharField(blank=True, max_length=20, null=True)),
                ('send_centent', models.CharField(blank=True, max_length=2048, null=True)),
                ('sms_phone', models.CharField(max_length=64)),
                ('sms_name', models.CharField(blank=True, max_length=64, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_sms',
                'managed': False,
            },
        ),
    ]
