# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POrder',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('order_limit', models.IntegerField(blank=True, null=True)),
                ('order_term', models.IntegerField(blank=True, null=True)),
                ('order_interest', models.FloatField(blank=True, null=True)),
                ('order_fee_sum', models.IntegerField(blank=True, null=True)),
                ('order_actual_money', models.IntegerField(blank=True, null=True)),
                ('order_repay_money', models.IntegerField(blank=True, null=True)),
                ('order_apply_time', models.IntegerField(blank=True, null=True)),
                ('order_approval_time', models.IntegerField(blank=True, null=True)),
                ('order_lend_time', models.IntegerField(blank=True, null=True)),
                ('order_appointment_repay_time', models.IntegerField(blank=True, null=True)),
                ('order_actual_repay_time', models.IntegerField(blank=True, null=True)),
                ('order_status', models.IntegerField(blank=True, null=True)),
                ('bind_card_status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField()),
                ('update_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'p_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('product_logo', models.CharField(max_length=1024)),
                ('product_limit_desc', models.CharField(max_length=512)),
                ('product_min_limit', models.IntegerField()),
                ('product_max_limit', models.IntegerField()),
                ('product_limit_unit', models.CharField(max_length=64)),
                ('product_limit_size', models.IntegerField()),
                ('product_speed_desc', models.CharField(max_length=512)),
                ('product_term_desc', models.CharField(max_length=512)),
                ('product_min_term', models.IntegerField()),
                ('product_max_term', models.IntegerField(blank=True, null=True)),
                ('product_term_unit', models.CharField(max_length=64)),
                ('product_term_size', models.IntegerField()),
                ('product_interest_desc', models.CharField(max_length=512)),
                ('product_ads_desc', models.CharField(max_length=512)),
                ('product_activity_desc', models.CharField(max_length=512)),
                ('repay_url', models.CharField(blank=True, max_length=512, null=True)),
                ('bind_card_url', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.IntegerField()),
                ('update_time', models.IntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
